/**
 * @license NgRx 9.0.0-beta.0+8.sha-4cae255
 * (c) 2015-2018 Brandon Roberts, Mike Ryan, Rob Wormald, Victor Savkin
 * License: MIT
 */
// TODO: @ngrx/component - remove this file
function sum(a, b) {
    return a + b;
}

/**
 * DO NOT EDIT
 *
 * This file is automatically generated at build
 */

/**
 * Generated bundle index. Do not edit.
 */

export { sum };
//# sourceMappingURL=component.js.map
